production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: swytchat_productiont
  pool: 5
  timeout: 5000
  username: postgres
  password: slar177

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: swytchat_development
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: swytchat_test
  pool: 5
  timeout: 5000
  username: postgres
  password: 123